### ISSUE TITLE
Can't run it.

### ISSUE THREAD

**Issue by Damienlee69** [milkdrop2077/MilkDrop3#1]
When i try to run the exe it says it can't run on my pc..? I don't know why that would be...any idea?
Win 10, i7, gtx 1080, 16gb ram.

**Comment by milkdrop2077** [comment]
did you setup the DirectX 9.0 Runtime files? maybe try again : https://www.microsoft.com/en-ca/download/details.aspx?id=35
show me the exact error message please

**Comment by Damienlee69** [comment]
I only downloaded the exe, now I grabbed the main and it works, noob. On that note, it's awesome that you're trying to resurrect the best visualizer that ever existed! Looks like there hasn't been any updates for awhile though. :( Still missing some key features for sure. Great work though. I can't help financially really, and know little coding, but if I can help somehow I'll try. Very least i can beta test, lol. Now I have to try and figure the create a preset thing and how to use them.

**Comment by Damienlee69** [comment]
K, so I still don't know what I'm doing wrong. I have a version of it working, but aside from space, not even H none of the shortcuts are working and I still don't know what the other exe is for. "milkdrop3.exe". I've installed the legacy directx as well.

**Comment by Damienlee69** [comment]
Ok, I'm so sorry for hassling you. Somehow the layout of the repo was confusing me, not sure what it was really. I grabbed from releases now and all good. This can be closed. I feel so stupid. But ya, my offer to help stands. Oh, there's no way to have the song title display from spotify I'm guessing?

**Comment by milkdrop2077** [comment]
If you want to help, you can create new double-presets (press 'f' twice, then f9, then space space space..., then save with 's') and send the best ones to me. Also I'm looking for cool Pattern images. Last job I want to group together and rename the similar presets with the 'R' letter, MilkDrop2077.RXXX, for example MilkDrop2077.R008 and MilkDrop2077.R009 are very similar, MilkDrop2077.R050 too. They should have a similar name or at least a close number, and try to credit the original's author if you can (like MilkDrop2077.R115 is cope - the drain to heaven) or create a new simple name.

**Comment by Damienlee69** [comment]
Is it supposed to always be double of the same preset? That's what it's saying with the names showing. By pattern images you mean screenshots of presets or external influence shots?

**Comment by Damienlee69** [comment]
I just thought it would be 2 different presets mixed: ex: R233 & R197 and it would say which are mixed when you have the names showing, but it's always just the same one twice.
The patterns, you just want me to keep an eye out for interesting geometric shaped?

**Comment by OfficialIncubo** [comment]
Simple. The patterns are the texture files. You should sample these in warp or comp shader.
