### ISSUE TITLE
MilkDrop 3 could not start audio capture..

### ISSUE THREAD

**Issue by nicsergio** [milkdrop2077/MilkDrop3#101]
I tried to use the fantastic milkdrop v3.27 with foobar and output via wasapi, but milkdrop cannot read the audio stream, starting milkdrop with playback already started the attached error message comes out: 

![Error](https://github.com/user-attachments/assets/7fd2d1f1-41a7-47c2-958a-53d7757ace23)

if I start milkdrop first it simply does not display any audio flow, am I doing something wrong?

**Comment by nicsergio** [comment]
Additional information: I am using foobar v2.24 32bit on Windows 10 with wasapi output support v3.4 plugin.
If I select an output mode without wasapi milkdrop3 works. 
Milkdrop v2 via shpeck plugin also works with wasapi output.
Thanks for the support.

**Comment by nicsergio** [comment]
Problem solved: I used the WASAPI SHARED OUTPUT plugin instead of WASAPI OUTPUT SUPPORT plugin, probably the latter was using the audio output in exclusive mode, now milkdrop3 works perfectly: awesome!
Thanks for the immense work.

**Comment by Gggggas** [comment]
I am getting the same Error on Output foo_dsd_asio , any suggestion? Thanks
