### ISSUE TITLE
Is there a tutorial to create your own presets?

### ISSUE THREAD

**Issue by go4ino** [milkdrop2077/MilkDrop3#2]
Hello I was wanting to try and create my own preset and didnt see any documentation on this github for how to do that.

**Comment by milkdrop2077** [comment]
Hey, I'm actually working on some video tutorials that I will post on YouTube soon! I made a tiny one on how to create a double-preset here : https://www.youtube.com/watch?v=vn7HSd4vSvM

Quick tutorial on how to create new double-presets using plasma3:
-press 'f' twice to switch to 'Show only classic-presets' (.milk files)
-press F9 to switch to 'Double Preset ON'
-press 'p' 4x times to force plasma3 transition
-you can press 'n' to show the debug information on the right
-load the first preset you want to mix (with the load key 'L') (preset1)
-load the second preset you want to mix (preset2)
-push the backspace key (go back to preset1)
-push the spacebar to start the transition (to preset2)
-push backspace, then spacebar,  backspace, then spacebar until you'll like the transition, the results will be different every time.
-press the 'c' key to change colours
-save your new double-preset (.milk2) pressing the key 's'
-choose a new name and press 'enter'

**Comment by milkdrop2077** [comment]
> Hello I was wanting to try and create my own preset and didnt see any documentation on this github for how to do that.

I made 2 videos about MilkDrop3 :
How to download and install : https://youtu.be/OQdZFlOHe5o
And all the new features explained : https://youtu.be/QBsDXPENe1I
