### ISSUE TITLE
The program can't start because d3dx9_43.dll is missing from your computer. Try reinstalling the program to fix this problem.

### ISSUE THREAD

**Issue by ayzick** [milkdrop2077/MilkDrop3#24]
This happened to me as I Installed this and Tried to open it 

Any way to fix this?

**Comment by milkdrop2077** [comment]
means your directx 9 runtimes dlls are not installed. Did you install directx9 files like on this video?: https://www.youtube.com/watch?v=OQdZFlOHe5o

**Comment by OfficialIncubo** [comment]
...or install the [DirectX Web Runtime](https://www.microsoft.com/en-US/download/details.aspx?id=35), then try to run this visualizer again.
Installing this will also support Pixel Shader 4!
