### ISSUE TITLE
Winamp

### ISSUE THREAD

**Issue by MxMaster3** [milkdrop2077/MilkDrop3#4]
Thanks for these great presets.
Is it possible to create a **vis_milk3.dll** so the presets can be loaded into Winamp?

**Comment by OfficialIncubo** [comment]
Milkdrop2077 (serge) told the great news past days that it can be run without any plugin for media players. It can be run as standalone instead.

**Comment by milkdrop2077** [comment]
Why do you want to run it with Winamp (and be limited to Winamp's audio only) when it can run better on it's own? 
No sorry I'm not planning on.

**Comment by powerdoll** [comment]
> Why do you want to run it with Winamp (and be limited to Winamp's audio only) when it can run better on it's own? No sorry I'm not planning on.

because there is no audio output directly from mkilkdrop3.exe
when on winamp you can stream the window visualizer and it will stream the audio too, directly
maybe using a virtual cable and all that but thats its too much work for something so simple
