### ISSUE TITLE
Delete mode not working for me

### ISSUE THREAD

**Issue by 3941** [milkdrop2077/MilkDrop3#40]
I'm always getting an error message: "unable to delete the file".

It's odd, because everything is in my user folder and should be freely accessible.
It also makes no difference when I run Milkdrop with elevated rights.

I installed some stupid 8k+ presets pack and figured I'd just use the delete function whenever I see ugly ones, but I guess it wasn't meant to be 😆

**Comment by milkdrop2077** [comment]
Hey I've found out that it doesn't work with win11, I've fixed it now, I'll publish a new version before xmas!

**Comment by milkdrop2077** [comment]
a patched version here with the delete mode that works on win11 : https://mega.nz/file/hNsh0JKI#G_guYmjWB-sTnGaKmgs9MBFn1mhGhgFPBvETk2HqnfQ

**Comment by milkdrop2077** [comment]
Hey @3941 if you can try this updated version for the delete mode, it should work well : https://mega.nz/file/wV1zFYga#2iBYxB5z-bMN6Z5h4InsJX_v8Y_M6WqtQZgaKfAYuqs

**Comment by milkdrop2077** [comment]
oh yes false positive are so annoying, antivirus are becoming paranoid if a program is not properly signed with a digital certificate (and that cost $$$). I've just tried it on a windows 11 pro laptop with all the update and did not get any warning with Microsoft defender though. Anyway I'm glad the delete mode is finally properly working, in the next version I'll try to move the presets in the bin instead of deleting them permanently :)

**Comment by 3941** [comment]
Huh, odd... Here's a shot, if you're interested.
I feel like Wacatac is a very common false positive... As someone who pirates things sometimes, I see it often.
![image](https://github.com/milkdrop2077/MilkDrop3/assets/8452538/76d574bf-d094-44d9-b7c5-76ca7a16efba)

**Comment by milkdrop2077** [comment]
Windows defender has different level of protection, I'm running a win11 with a local account = lowest protection (you need to be signed in a Microsoft account to get the 'highest' level, that's probably why

**Comment by 3941** [comment]
Ah, cloud protection or something, probably. I am indeed signed in. Makes sense.

**Comment by milkdrop2077** [comment]
Hey @3941, I've finished MilkDrop 3.24, can you please try it to see if the false positive that appear when I've changed the delete-mode is gone? please let me know
download : https://mega.nz/file/BccEWCyb#xv1BMdBxPMSrH079UQ88HYPOwkKGq9oR3xK981Z6ytw
Or someone else, need to have a win11 with an user signed in a Microsoft account.

**Comment by 3941** [comment]
Well, that's awkward... I just got the email from your response and guess what I'm doing just this moment? 
I'm installing Bitdefender Free to give it a try... 😬 
Which ofc disables Windows Defender...
If I can just switch them somehow, without uninstalling, I'll try. Otherwise, it'll have to wait until I come to hate Bitdefender, which is very well possible to happen shortly.

**Comment by milkdrop2077** [comment]
Bitdefender is crap. stick to windows defender ;)

**Comment by 3941** [comment]
It's good at detecting things as they are. When it deletes keygens, it'll tell you it deletes keygens, not some random trojan.
But it's super inconvenient otherwise. I like to have more control over things and it gave me almost none. Hated it.
So, back to Windows Defender, which isn't much better and detects a lot of junk...

Anyways, I'm not getting a detection on this one. I even unallowed all the "allowed threats" I had in Defender, in case those aren't "bound" to specific files (and actually it looks like they aren't, which makes that a HORRIBLE mechanic).
