### ISSUE TITLE
Request:  Android port.

### ISSUE THREAD

**Issue by dethzord** [milkdrop2077/MilkDrop3#41]
Long shot.  Any chance you might port this to Android?  Would be kinda slick with an Android TV box on a home theater.  Guessing not, but hey, maybe it's something on your list.

**Comment by OfficialIncubo** [comment]
There's no way to port with Android. It requires DirectX 9 in order to run Milkdrop3/BeatDrop.
Please try [projectM for Android](https://play.google.com/store/apps/details?id=com.psperl.prjM&hl=en_US) instead.

**Comment by dethzord** [comment]
I've got projectM.
