### ISSUE TITLE
Spout paramater control or other interface support ?

### ISSUE THREAD

**Issue by Treide1** [milkdrop2077/MilkDrop3#47]
Hey there,

first of all: great work! 
I went for the paid version MilkDrop3.30 on buy-me-a-coffee and I enjoy the Spout support. 

Is there a way to control Milkdrop 3 via Spout or some other interface ?
I.e. drive commands from external sources like triggering a softcut or specifically setting the color instead of getting a random one.

I want to control Milkdrop 3 from OPENRNDR (on the Java Virtual Machine) or Resolume with the highest degree of control possible.
Thanks in advance !

**Comment by milkdrop2077** [comment]
Hey thanks for the support!
I'm working on a proper GUI for VJ to control milkdrop in way that is never been done before, 
you'll be able to control everything basically, you'll be able to change the RGB values individually... well everything :)
I hope to get a first version ready before the end of the winter/spring!

**Comment by Treide1** [comment]
Wow, looking forward to that then :D
