### ISSUE TITLE
Transparency? Possibility of making it open source?

### ISSUE THREAD

**Issue by 0xab4d1d3a** [milkdrop2077/MilkDrop3#5]
I want to use this (and support you on patreon) but can't in good confidence just download (or recommend to my friends to download) a random .exe hosted on github.

Any plans for making it open source?

**Comment by 0x5066** [comment]
It's becoming interesting when you consider the fact that this repository states it's based on Beatdrop (though unclear if it's based on the original iteration or by Incubo), which is licensed under the BSD 3-Clause, while not required to ship the source code, although appreciated, the author MUST include the license notice.

https://www.tldrlegal.com/license/bsd-3-clause-license-revised

It should also be noted that the point of Github is for Open Source software, not Closed Source software.

**Comment by OfficialIncubo** [comment]
> It's becoming interesting when you consider the fact that this repository states it's based on Beatdrop (though unclear if it's based on the original iteration or by Incubo), which is licensed under the BSD 3-Clause, while not required to ship the source code, although appreciated, the author MUST include the license notice.
> 
> https://www.tldrlegal.com/license/bsd-3-clause-license-revised
> 
> It should also be noted that the point of Github is for Open Source software, not Closed Source software, like this repository.

I am not the original author of BeatDrop Music Visualizer, but it belongs to Maxim Volskiy. I also mentain the improvement one.

**Comment by 0x5066** [comment]
Great, I did not state you as the original author. 🙂

**Comment by milkdrop2077** [comment]
> I want to use this (and support you on patreon) but can't in good confidence just download (or recommend to my friends to download) a random .exe hosted on github.
> 
> Any plans for making it open source?

Not all closed source project are evil and I'm perfectly allowed to distribute a closed source project here.
I would understand your suspicions if I popped out of nowhere asking people to download MilkDrop3.exe but I think I've been around for quite a while now, I made MilkDrop2077 and BeatDrop2077 open-sourced, I think I can be trusted. 
MilkDrop3.exe is very similar to BeatDrop2077.exe, it's does not require any administrator permission, does not connect to the internet. I'm actively developing it at the moment and I don't feel like sharing the source for the time been, maybe later, I'm sure you can understand that.

**Comment by 0xab4d1d3a** [comment]
I'm sure you can understand the iterative nature of how code is pushed/maintained on Github doesn't require it to be mutually exclusive why you can't continue developing it while also making it open source.

I look forward to fully supporting you when you change your mind. Best of luck on progress in the mean time.

**Comment by milkdrop2077** [comment]
> I'm sure you can understand the iterative nature of how code is pushed/maintained on Github doesn't require it to be mutually exclusive why you can't continue developing it while also making it open source.
> 
> I look forward to fully supporting you when you change your mind. Best of luck on progress in the mean time.

https://www.youtube.com/watch?v=QBsDXPENe1I

**Comment by 0x5066** [comment]
That doesn't answer @0xab4d1d3a's inquiry...?
And why haven't you included the BSD 3-Clause license text that you **have** to include?

**Comment by milkdrop2077** [comment]
yeah it helps to make an opinion :)
another thing to help, run it into a sandbox, windows has a free sandbox, check the about in the installer, 
that's called coding for the love. 
The licence is already here already : https://www.youtube.com/watch?v=OQdZFlOHe5o&t=68s

**Comment by OfficialIncubo** [comment]
I just saw the license text file and both BeatDrop and Milkdrop2 Music Visualizer are licensed under the BSD 3-Clause!

**Comment by 0x5066** [comment]
Yes, and this is why I brought up my comment in the first place.

The video doesn't act as a license in any sensible way, it just doesn't fulfill the requirements by the BSD 3-Clause.

**Comment by 0x5066** [comment]
To beat a dead horse, the Source Code that exists in this repo is from **BeatDrop2077** and not MilkDrop3, this can easily be compared against by looking at [text1.bin](https://github.com/milkdrop2077/MilkDrop3/blob/main/code/vis_milk2/text1.bin) and what is provided by the F1 screen in MilkDrop3.

![image](https://github.com/milkdrop2077/MilkDrop3/assets/38136789/9a095754-8878-418a-97d5-2d93c27d5ac2)

This program is not open source, it's just reposting the BeatDrop2077 code.

**Comment by milkdrop2077** [comment]
It's the weekend don't you have anything better to do? 
We literally talked in this same page that it's not open source. 
Stop acting like you're the sjw godfather of winamp and milkdrop, you're not.
