### ISSUE TITLE
Has anyone ever though about porting this to linux ?

### ISSUE THREAD

**Issue by etiennemlb** [milkdrop2077/MilkDrop3#52]
What would be the largest hurdle ?

**Comment by milkdrop2077** [comment]
Short answer, yes :)
You have 2 alternative options:
- Use projectM, it's a fantastic software.
- Or run it in some kind of virtualization software like wine (I haven't tried it yet)

**Comment by etiennemlb** [comment]
Yep, then projectM it is.
Thanks.

**Comment by cynthia2006** [comment]
Why is it not portable to Linux?
