### ISSUE TITLE
Source does not match .exe

### ISSUE THREAD

**Issue by skraninger** [milkdrop2077/MilkDrop3#56]
Why is the source compiling beatdrop.exe rather than milkdrop3.exe?

**Comment by milkdrop2077** [comment]
Hi Steven, MilkDrop3 is based on BeatDrop from Maxim Volskiy. The full source code is not publicly available.
The source on github is an alpha version based on my BeatDrop2077. I keep it there because occasionally, people ask questions, and I use it to reference specific parts of the code.
