### ISSUE TITLE
My Milkdrop3 Double Preset Pack! [NOT AN ISSUE]

### ISSUE THREAD

**Issue by OfficialIncubo** [milkdrop2077/MilkDrop3#6]
I decided to upload some milk2 presets I made past days because of my special easter trip that I have today.

Download it now! ~~https://mega.nz/folder/hcBB1RzL#Jy8GfuiB9WiBOKxEJ4pbhQ~~
https://forums.winamp.com/forum/visualizations/milkdrop/milkdrop-presets/4623131-my-milkdrop-presets-collection

**Comment by hcube7** [comment]
Thank you so much! These are epic! :D

**Comment by OfficialIncubo** [comment]
@milkdrop2077, why don't you try my double preset pack for free?

@hcube7, you're welcome! I am trying to make more double presets in the future if I can.

**Comment by milkdrop2077** [comment]
@OfficialIncubo I've tried, you can do better.
watch this https://www.youtube.com/watch?v=AdcUPpp1O0k again and again until you do something nicer ;)

**Comment by OfficialIncubo** [comment]
This time, I have included my .milk2 presets into my preset pack! You can check in my first post!
