### ISSUE TITLE
Refreshing messages.ini with BACKSPACE doesn´t work

### ISSUE THREAD

**Issue by ElSyndrome** [milkdrop2077/MilkDrop3#86]
Hello,
At first thank you for developing this program. Really great!
I'm trying to make a python program to show lyrics in Milkdrop3, but now I can´t seem to refresh the messages.ini file after it was altered. It should be done with the backspace button according to instructions in the file itself.
Is this a known issue or is there another way to do this?  
Thanks
Jelle

**Comment by milkdrop2077** [comment]
Hello @ElSyndrome 

That sounds awesome! 
I could quickly code a custom API if you'd like. 
You could send messages directly to MilkDrop3 using SendMessage, it's a much faster and easier solution.

For example, you could send something like this:  **MESSAGE|hello this is the lyrics|1.2**
Here, 1.2 would represent the time (in seconds) to display the message. 
We could even extend it with more parameters, like this:  
**MESSAGE|hello this is the lyrics|1.2|0.8|0.5|Arial|FFFFAA|24**
This could include XY position, font, size, color, etc.

I already have a function that reads and processes this:
_(WCHAR* szText, float fSize, float x, float y, float growth, float fTime, float fFade, const WCHAR* szFace, bool bItal, bool bBold, int nColorR, int nColorG, int nColorB, float randx, float randy, int nRandR, int nRandG, int nRandB)_

Does that work for you? Or if your time is limited, I can start with the INI file solution. Let me know what’s best!
Thanks!

**Comment by ElSyndrome** [comment]
Wow thanks for that quick reply! That api solution with sendmessage sounds perfect! Especially with the extra parameters… :-)

I already got it working for sprites (to show album-covers/artist-images or random photo’s) because the images.ini file doesn’t need to be refreshed. But maybe in the future a similar solution for sprites could be added as well.. ;-)

Thanks !

**Comment by milkdrop2077** [comment]
Here is an alpha version:
https://www.dropbox.com/scl/fi/7junw9q6mkv5g8qzy5h7f/MilkDrop3-msg.zip?rlkey=oyu10wftyupg4znr6r355l6zu&st=vngf580n&dl=0

Just find the window 'MilkDrop 3.26 - Press F1 for help' and use a SendMessage to send:
**MSG|text=this is a test|size=52|time=5|x=0.5|y=0.7**

```
text={textstring}               // The text string to show for this custom message (max 256 characters)
font={fontname}                 // The font name to use
size={int:0..100}               // The font size (0=tiny, 100=enormous, 40-60=normal range)
growth={float:0.25..4.0}        // The factor to grow or shrink over time (0.5=shrink to half-size, 2.0=grow to double size)
x={float:0..1}                  // The x-position of the center of the text (0.0=left side, 1.0=right side)
y={float:0..1}                  // The y-position of the center of the text (0.0=top, 1.0=bottom)
randx={float:0..1}              // X-randomization: x will be bumped within +/- this value
randy={float:0..1}              // Y-randomization: y will be bumped within +/- this value
time={float:0..999}             // The duration (in seconds) the text will display
fade={float:0..1}               // The percentage of time (0..1) spent fading in the text
ital={0|1}                      // Font italics override (0=off, 1=on)
bold={0|1}                      // Font bold override (0=off, 1=on)
r={int:0..255}                  // Red color component for the font
g={int:0..255}                  // Green color component for the font
b={int:0..255}                  // Blue color component for the font
randr={int:0..255}              // Randomization for the red component (r will be bumped within +/- this value)
randg={int:0..255}              // Randomization for the green component (g will be bumped within +/- this value)
randb={int:0..255}              // Randomization for the blue component (b will be bumped within +/- this value)
```

examples:
**MSG|text=this is a test|size=52|time=5|x=0.5|y=0.7
MSG|font=Courier New|text=testing|size=62|time=3|x=0.1|y=0.2|bold=1
MSG|font=Arial|text=Hello!|size=32|time=3.5|x=0.5|y=0.5|bold=1|r=255|randg=100|growth=2.0**
...

You can include only the parameters you need to change! Let me know how it goes, I’m excited to hear your feedback :)

**Comment by milkdrop2077** [comment]
Send the message 'test' to check if MilkDrop3 has received it; this will trigger a message box. 
Always begin your messages with 'MSG|' and use '|' as the delimiter between parameters!

**Comment by ElSyndrome** [comment]
Great, as soon as I have time I will dive into it. First I have to find out how to send a string with sendmessage... (My coding skills are in development mode ;))
Thanks and I'll let you know! :)

**Comment by ElSyndrome** [comment]
Hello! I'm trying to find out how to send the message to the window but haven´t managed to succeed yet. Most probably I'm doing something wrong... 

This is the code and some sendmessages I've tried:
    windowid = win32gui.FindWindow(None, "MilkDrop 3.26 - Press F1 for help")  # **This works**
    print(windowid)
    message = 'MSG|font=Arial|text=test|size=32|time=3.5|x=0.5|y=0.5|bold=1|r=255|randg=100|growth=2.0' #   'test'  
    
    #win32gui.SendMessage(windowid, win32con.WM_USER, 0, message) # **Does nothing**

    #win32gui.SendMessage(windowid, win32con.WM_SETTEXT, None , message)     # **This changes the title of the window(Milkdrop)**
    
    #win32gui.SendMessage(windowid, win32con.WM_USER+100, 0, message)  # **Does nothing**

Maybe you'll see immediately what I'm doing wrong and have a tip?
Either way, I'll keep searching...

**Comment by milkdrop2077** [comment]
Ok so first, for the test function, only send the string 'test', nothing else.
Then try: **MSG|text=this is a test|size=52|time=5|x=0.5|y=0.7**
You don't need any other fancy parameters.

Here is how I do it in pascal:

```
var
  hwndx: HWND;
  cds: COPYDATASTRUCT;
  msgText: WideString;
begin

  hwndx := FindWindow(nil, 'MilkDrop 3.26 - Press F1 for help');  // Find the window
  msgText := 'MSG|text=this is a test|size=52|time=5|x=0.5|y=0.7';  // Prepare the message

  cds.dwData := 0; 
  cds.cbData := (Length(msgText) + 1) * SizeOf(WideChar); // Size of the string, including null terminator
  cds.lpData := PWideChar(msgText);  // Pointer to the string

  SendMessage(hwndx, WM_COPYDATA, WPARAM(Application.Handle), LPARAM(@cds));   // Send the message
```


I think I've forgot to mention to use WM_COPYDATA :)
Ask chatGPT to write you a small example, it's very good for this kind of stuff!

**Comment by ElSyndrome** [comment]
Thanks for that info! It put me on the right track! It is working now, the python code I used for this:

class COPYDATASTRUCT(ctypes.Structure):
    _fields_ = [
        ('dwData', ctypes.wintypes.LPARAM),
        ('cbData', ctypes.wintypes.DWORD),
        ('lpData', ctypes.c_wchar_p) 
        #formally lpData is c_void_p, but we do it this way for convenience
    ]
    
FindWindow = ctypes.windll.user32.FindWindowW
SendMessage = ctypes.windll.user32.SendMessageW
windowid = win32gui.FindWindow(None, "MilkDrop 3.26 - Press F1 for help")
if windowid == 0:
    print("Could not find 'MilkDrop 3.26 - Press F1 for help'-window")
message = 'MSG|font=Arial|text=This is a test!|size=32|time=3.5|x=0.5|y=0.5|bold=1|r=155|randg=100|growth=2.0' #   'test'  
#message = 'test'
cds = COPYDATASTRUCT()
cds.dwData = 0
cds.cbData = ctypes.sizeof(ctypes.create_unicode_buffer(message))
cds.lpData = ctypes.c_wchar_p(message)
#win32gui.SendMessage(windowid, win32con.WM_SETTEXT, None , message)     # This changes the title of the window(Milkdrop)
SendMessage(windowid, win32con.WM_COPYDATA, 0, ctypes.byref(cds))

Awesome and thank you for the support and quick reply's!  :-)

**Comment by IkeC** [comment]
I wrote a litte standalone tool that works well with the alpha version you posted, but not with 3.27 unfortunately.

![Image](https://github.com/user-attachments/assets/1e581d12-6832-415c-bd7f-8538b72e8c3b)

**Comment by milkdrop2077** [comment]
Hey @IkeC that's great! Sadly, I did not continue this because all the versions I've compiled tested positive in Windows Defender...
I think I need to replace the SendMessage part with a shared memory segment, because it seems like AV don't like SendMessage. 

If you want to share your standalone version, I'm sure some people would be interested!

**Comment by IkeC** [comment]
> Hey [@IkeC](https://github.com/IkeC) that's great! Sadly, I did not continue this because all the versions I've compiled tested positive in Windows Defender... I think I need to replace the SendMessage part with a shared memory segment, because it seems like AV don't like SendMessage.
> 
> If you want to share your standalone version, I'm sure some people would be interested!

Well if it only works with a special (outdated) version, I'm not sure if it makes sense. I had no problems with AV and your alpha version. Maybe you could supply an alternate version of 3.27 containing this feature?

**Comment by milkdrop2077** [comment]
I'm about to publish the 3.28 version. I'll do a version that support the SendMessage, I'll post it here soon.

**Comment by IkeC** [comment]
> Sending a message from this program using BeatDrop, and also MilkDrop 3 doesn't work. Except the Send Keys still works!

Sending messages currently only works with the Alpha version posted above.

**Comment by OfficialIncubo** [comment]
I have been waiting for BeatDrop and the release version of MilkDrop3 support.
Then I can try if it works.

**Comment by milkdrop2077** [comment]
@IkeC looks good!
