### ISSUE TITLE
"30.0" is an invalid float

### ISSUE THREAD

**Issue by exosphaer3** [milkdrop2077/MilkDrop3#89]
Can't start the timer for automatic transitions. Reinstalled, opened it and without any changes following is shown when pressing the timer (top middle button):

![vIzfWpiqCY](https://github.com/user-attachments/assets/6f4adf28-4b2b-493c-8f68-cebaf88ccaff)

Trying to change the "time between presets" in "controls" lead to the same error message.

Maybe related: Under "startup" I can't make any number a float since I can't enter a dot.

Windows 11 Version	10.0.22631 Build 22631
Local language is set to german

**Comment by exosphaer3** [comment]
Sorry, my bad. Tab wasn't choosen. TRansitions are working now.

**Comment by milkdrop2077** [comment]
Hello I've patched this bug (due to the german language that's forcing the float number to be with a ',' instead of a '.' in the next version coming up in a few days, please contact me via email, I'll send you the patched version
